### ISSUE TITLE
Parse `gcc` errors to help locate resources 

### ISSUE THREAD

**Issue by aakropotkin** [nixpkgs-architecture/issues#19]
Mostly posting this to expand it later and don't forget.

`gcc` can dump errors as JSON which would allow scraping of missing headers and libs to assist iteration when packing new programs.

Hooked into something like `nix-index` or `pkg-config` we could even emit helpful messages with recommended dependencies to add.

**Comment by DavHau** [comment]
@ritobezarius and @mic92 are working on something related: https://github.com/RaitoBezarius/buildxyz

**Comment by Mic92** [comment]
Yes. We basically do exactly that. Use nix-index and a Fuse filesystem to parse files accessed by a build and make suggestions about missing dependencies.

**Comment by infinisil** [comment]
Is this relevant for Nixpkgs architecture? I'd think a normal Nixpkgs issue would be better for this
