### ISSUE TITLE
Unable to find meeting videos

### ISSUE THREAD

**Issue by toraritte** [nixpkgs-architecture/issues#9]
**Issue description**

The [Nixpkgs Architecture Team  overview](https://github.com/nixpkgs-architecture) states that 

> Every meeting is live-streamed/uploaded to the [NixOS YouTube channel](https://www.youtube.com/c/NixOS-Foundation) for later viewing. Meeting notes are taken on https://pad.lassul.us/ and later committed to https://github.com/nixpkgs-architecture/meetings.

but I couldn't find the meeting videos on that youtube channel. (The meeting notes are great, but was still curious.)

**Goal**

If it was me and just couldn't find them, maybe create a playlist to make them easier to discover, or if they are really not there, then please upload them. Thank you!

**edit**: [Was able to find them](https://www.youtube.com/channel/UC_BFweJOiukTHdKCr1P0kRQ/featured), so maybe the link just needs to be updated in the overview?

**Comment by infinisil** [comment]
Ah yes, thanks for pointing that out, I committed the change locally but didn't push it. Did so now in https://github.com/nixpkgs-architecture/.github/commit/4e60257e13340cffe161d90ee02f51cc6a74c087

The channel the meeting notes are available is the new [Nixpkgs Architecture Team channel](https://www.youtube.com/channel/UC_BFweJOiukTHdKCr1P0kRQ)
